version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
          - ovsql_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./_docker/php-fpm
        #image: php:7.3-fpm
        container_name: ov_php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html:cached
        depends_on:
            - db
        links:
            - db
        extra_hosts:
            - "ondravotava.test:172.20.0.4" #ip addr is nginx add can be changed

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./_docker/nginx/symfony.conf:/etc/nginx/sites-enabled/default:ro
            - ./:/var/www/html:cached

volumes:
  ovsql_volume:
