easy_admin:
    entities:
        Certification:
            class: App\Entity\Certification
            list:
                fields:
                    - 'title'
                    - { property: 'when', format: 'm/Y' }
                    - 'description'
            form:
                fields:
                 - { property: 'title', css_class: 'large' }
                 - { property: 'when', type: 'App\Admin\Field\DateType'}
                 - 'description'
