easy_admin:
    entities:
        Snippet:
            class: App\Entity\Snippet
            list:
                fields:
                    - 'snippetId'
                    - 'text'
            form:
                fields:
                 - { property: 'snippetId', css_class: 'large' }
                 - 'text'
