easy_admin:
    entities:
        SocialLink:
            class: App\Entity\SocialLink
            list:
                fields:
                    - 'title'
                    - 'icon'
                    - 'link'
            form:
                fields:
                 - { property: 'title', css_class: 'large' }
                 - { property: 'link', css_class: 'large' }
                 - { property: 'icon', css_class: 'large' }
